name: Jonathan Sick
port: 4001
pygments: true
exclude: ["vendor", "assets/vendor", "Gemfile", "Gemfile.lock"]
markdown: redcarpet
permalink: /:year/:month/:day/:title
redcarpet:
      extensions: ["smart"]
